apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-abcd-prefix
  namespace: default
spec:
  stripPrefix:
    prefixes:
      - /code-abcd-service

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-ingress
  annotations:
    # Cú pháp: <namespace>-<tên-middleware>@kubernetescrd
    traefik.ingress.kubernetes.io/router.middlewares: default-strip-abcd-prefix@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
  - http:
      paths:
      - path: /code-abcd-service
        pathType: Prefix
        backend:
          service:
            name: code-abcd-service
            port:
              number: 80