apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: doppler-secret
  namespace: default
spec:
  tokenSecret:
    name: doppler-token-secret
  managedSecret:
    name: app-env-secrets
    namespace: default
    type: Opaque

---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: doppler-registry-secret
  namespace: default
spec:
  tokenSecret:
    name: doppler-token-secret
  managedSecret:
    name: docker-pull-secret
    namespace: default
    type: kubernetes.io/dockerconfigjson
  secretsMapping:
    .dockerconfigjson: DOCKER_REGISTRY_CONFIG